
--Diplomacy
NDefines.NDiplomacy.CHANGE_RIVAL_YEARS = 10
NDefines.NDiplomacy.DISHONORABLE_PEACE_MONTHS = 0
NDefines.NDiplomacy.DESIRED_NUM_OF_ELECTORS = 8
NDefines.NDiplomacy.MAX_NUM_OF_ELECTORS = 8
NDefines.NDiplomacy.JOIN_HRE_DEVELOPMENT_CAP_VASSAL = 200
NDefines.NDiplomacy.IMPERIAL_AUTHORITY_FROM_PRINCES = 0.05			
NDefines.NDiplomacy.INTEGRATE_UNION_MIN_YEARS = 30 --Mainly for burgundy
NDefines.NDiplomacy.MIN_RELATIONS_TO_ALLY = -200
NDefines.NDiplomacy.MONTHS_BEFORE_TOTAL_OCCUPATION = 12
NDefines.NDiplomacy.AE_HRE_INTERNAL = 0.35

--Country
NDefines.NCountry.PROSPERITY_MONTHLY_DECLINE = -2			
NDefines.NCountry.PROSPERITY_INCREASE_SIZE = 2
NDefines.NCountry.MONARCH_MIN_SKILL = 1
NDefines.NCountry.DISINHERIT_PRESTIGE_HIT = -25
NDefines.NCountry.LAND_FORCELIMIT_EXTRA_COST_FACTOR = 2.5
NDefines.NCountry.SCRIPTED_ADVISOR_DISCOUNT = 0.7  
NDefines.NCountry.MAX_IDEA_GROUPS_FROM_SAME_CATEGORY = 0.4
NDefines.NCountry.PS_REPLACE_RIVAL = 0

--NationDesigner
NDefines.NNationDesigner.FLAT_TAX_AMOUNT = 5



NDefines.NMilitary.WARGOAL_MAX_BONUS = 40
NDefines.NMilitary.SLACKEN_AP_DROP = 0.05
NDefines.NMilitary.SLACKEN_MANPOWER_INCREASE = 1.5
NDefines.NMilitary.BASE_MP_TO_MANPOWER = 0.30
NDefines.NMilitary.CREATE_JANISSARIES_MIL_COST = 8
NDefines.NMilitary.ARMY_DRILL_YEARLY_DECAY = -1.5


--Economy
NDefines.NEconomy.BANKRUPTCY_BUILDING_DESTRUCTION_THRESHOLD = 10
NDefines.NEconomy.DEBASE_MAX_CORRUPTION = 30
NDefines.NEconomy.BANKRUPTCY_PROVINCE_DEVASTATION_GAIN = 20
